USE [master]
GO

/****** Object:  Database [StockDatabasesX]    Script Date: 16/2/2024 14:15:00 ******/
CREATE DATABASE [StockDatabasesX]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'StockDatabasesX', FILENAME = N'K:\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\StockDatabasesX.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'StockDatabasesX_log', FILENAME = N'K:\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\StockDatabasesX_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [StockDatabasesX].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [StockDatabasesX] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [StockDatabasesX] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [StockDatabasesX] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [StockDatabasesX] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [StockDatabasesX] SET ARITHABORT OFF 
GO

ALTER DATABASE [StockDatabasesX] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [StockDatabasesX] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [StockDatabasesX] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [StockDatabasesX] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [StockDatabasesX] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [StockDatabasesX] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [StockDatabasesX] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [StockDatabasesX] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [StockDatabasesX] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [StockDatabasesX] SET  DISABLE_BROKER 
GO

ALTER DATABASE [StockDatabasesX] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [StockDatabasesX] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [StockDatabasesX] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [StockDatabasesX] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [StockDatabasesX] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [StockDatabasesX] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [StockDatabasesX] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [StockDatabasesX] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [StockDatabasesX] SET  MULTI_USER 
GO

ALTER DATABASE [StockDatabasesX] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [StockDatabasesX] SET DB_CHAINING OFF 
GO

ALTER DATABASE [StockDatabasesX] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [StockDatabasesX] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [StockDatabasesX] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [StockDatabasesX] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [StockDatabasesX] SET QUERY_STORE = ON
GO

ALTER DATABASE [StockDatabasesX] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [StockDatabasesX] SET  READ_WRITE 
GO

